/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bbms;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class StockIncreased extends javax.swing.JFrame {

    /**
     * Creates new form StockIncreased
     */
    public StockIncreased() {
        initComponents();
        stock();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    
    
    public void stock(){
      DefaultTableModel dtm=(DefaultTableModel)TableDisplay.getModel();
        dtm.setRowCount(0);
        try{
            Connection con=dbConnection.getCon();
            Statement stmt = con.createStatement();
           ResultSet rs=stmt.executeQuery("select * from stock");
           while(rs.next()){
               dtm.addRow(new Object[]{rs.getString(1),rs.getString(2)});
           }
        }
        catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BloodGroup = new javax.swing.JLabel();
        blood = new javax.swing.JComboBox<>();
        Units = new javax.swing.JLabel();
        unit = new javax.swing.JTextField();
        UpdateBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDisplay = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        PrintBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(370, 200));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        Heading.setText("Stock(Increased)");
        getContentPane().add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 6, 366, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 857, 10));

        BloodGroup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BloodGroup.setText("Blood Group");
        getContentPane().add(BloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 91, 90, -1));

        blood.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        getContentPane().add(blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 88, -1, -1));

        Units.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Units.setText("Units");
        getContentPane().add(Units, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 91, 38, -1));

        unit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 88, 104, -1));

        UpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save.png"))); // NOI18N
        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 88, 113, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 146, 857, 11));

        TableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "BloodGroup", "Units"
            }
        ));
        jScrollPane1.setViewportView(TableDisplay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 184, 615, 255));

        jSeparator3.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 467, 857, 11));

        PrintBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PrintBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/print.png"))); // NOI18N
        PrintBtn.setText("Print");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PrintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 512, -1, -1));

        CloseBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cancel.png"))); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 516, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset.png"))); // NOI18N
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 88, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bg.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        // TODO add your handling code here:
        try{
            TableDisplay.print(JTable.PrintMode.NORMAL);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Connection con=dbConnection.getCon();
            Statement stmt = con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from bloodgrp");
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_formComponentShown

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        String bloodgrp=(String)blood.getSelectedItem();
        String units=unit.getText();
        int unit1=Integer.parseInt(units);
        try{
            Connection con=dbConnection.getCon();
            Statement stmt = con.createStatement();
           
JOptionPane.showMessageDialog(null, "Connected");
stmt.executeUpdate("insert into bloodbankmanagement.stock(bloodgrp,units)values('"+bloodgrp+"','"+units+"')");
JOptionPane.showMessageDialog(null, "added sucessfully");
            setVisible(false);
            new StockIncreased().setVisible(true);
        }
        catch(Exception e){
            System.out.println(e);
                        JOptionPane.showMessageDialog(null, "Error adding blood group");
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockIncreased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockIncreased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockIncreased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockIncreased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockIncreased().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BloodGroup;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JTable TableDisplay;
    private javax.swing.JLabel Units;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JComboBox<String> blood;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField unit;
    // End of variables declaration//GEN-END:variables
}
